---
#tasks file for setup_env
- include_tasks: config_env_centos_7.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: config_env_ubuntu_18.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

