---
# tasks file for kibana_install
- include_tasks: install_kibana_centos_7.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: install_kibana_ubuntu_18.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: '#server.host: "localhost"'
   line: 'server.host: "0.0.0.0"'
   
- name: Restart kibana
  service:
    name: "{{ package_kibana }}"
    enabled: true
    state: started