---
# defaults file for setup_env
packages_slt_centos:
  - git 
  - wget
  - curl
  - byobu
  - pwgen
elpel_release_package:
  - epel-release
chrony_package: chrony
ntp_name_service: chronyd
java_package_centos: java-1.8.0-openjdk

# Var config for ubuntu 
webserver_package: nginx

packages_slt_ubuntu:
  - apt-transport-https
  - wget 
  - git
  - curl
  - gnupg
  - gnupg2
  - gnupg1

java_package_ubuntu: openjdk-8-jre