---
- name: Install sidecar reposetory
  shell: rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-sidecar-repository-1-2.noarch.rpm

- name: update system
  yum:
    name: '*'
    state: latest

- name: Install graylog-sidecar 
  yum:
    name: graylog-sidecar
    state: present

- copy: 
    src: /etc/graylog/sidecar/sidecar.yml
    dest: /etc/graylog/sidecar/sidecar.yml.bk
    remote_src: yes

- replace:
    path: /etc/graylog/sidecar/sidecar.yml
    regexp: '#server_url: "http://127.0.0.1:9000/api/"'
    replace: 'server_url: "http://{{ ip_graylog_server }}:9000/api/"'
    backup: yes

- replace:
    path: /etc/graylog/sidecar/sidecar.yml
    regexp: 'server_api_token: ""'
    replace: 'server_api_token: "{{ api_token }}"'
    backup: yes

- replace:
    path: /etc/graylog/sidecar/sidecar.yml
    regexp: '#log_path: "/var/log/graylog-sidecar"'
    replace: 'log_path: "/var/log/graylog-sidecar"'
    backup: yes

- replace:
    path: /etc/graylog/sidecar/sidecar.yml
    regexp: '#tls_skip_verify: false'
    replace: 'tls_skip_verify: true'
    backup: yes

- replace:
    path: /etc/graylog/sidecar/sidecar.yml
    regexp: '#node_name: ""'
    replace: 'node_name: "{{ name_server }}"'
    backup: yes

- name: install sidecar
  shell: graylog-sidecar -service install

- name: restart graylog-sidecar
  service:
    name: "graylog-sidecar"
    enabled: true
    state: restarted