---
- name: install elpel-release
  yum:
    name: "{{ elpel_release_package }}"
    state: present

- name: update system
  yum:
    name: '*'
    state: latest

- name : install packages supplementary
  yum:
    name: "{{ packages_slt }}"
    state: present

- name: install java
  yum:
    name: "{{ java_package }}"
    state: present

- name: install chrony
  yum:
    name: "{{ chrony_package }}"
    state: present

- name: update file config chrony
  lineinfile: dest=/etc/chrony.conf regexp={{ item.regexp }} line={{ item.line }}
  with_items:
  - {'regexp': "server 0.centos.pool.ntp.org iburst", 'line': "server {{ip_ntp_server}} iburst"}
  - {'regexp': "server 1.centos.pool.ntp.org iburst", 'line': "#server 1.centos.pool.ntp.org iburst"}
  - {'regexp': "server 2.centos.pool.ntp.org iburst", 'line': "#server 2.centos.pool.ntp.org iburst"}
  - {'regexp': "server 3.centos.pool.ntp.org iburst", 'line': "#server 3.centos.pool.ntp.org iburst"}

- name: Start ntp service
  service:
    name: "{{ ntp_name_service }}"
    enabled: true
    state: restarted

- name: config disable selinux
  shell: '{{item}}'
  with_items:
  - sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
  - sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config