---
# tasks file for elastic_install

- include_tasks: install_elastic_centos_7.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: install_elastic_ubuntu_18.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Restart elasticsearch
  service:
    name: "{{ package_elastic }}"
    enabled: true
    state: started