---
# logstash install centos
- name: add repo logstash
  template:
    src: repo-logstash.j2
    dest: /etc/yum.repos.d/logstash.repo

- name: Install logstash 
  yum: 
    name: "{{ package_logstash }}"
    state: present